### ISSUE TITLE
Packagist

### ISSUE THREAD

**Issue by AurelienLavorel** [lyra/plugin-magento#1]
Add module to Packagist

**Comment by nabil509** [comment]
Thank you. We will do it but not immediately. We are refactoring module architecture to use our separate payment library. We also have to do another refactoring to produce one payment module for all our clients in different countries.

**Comment by sprankhub** [comment]
Status?

**Comment by sprankhub** [comment]
@GIMALima, @nabil509, this is not fixed yet. https://packagist.org/?query=lyranetwork%2F shows only two packages, which are not Magento modules:

![image](https://github.com/lyra/plugin-magento/assets/930199/ae7bca9c-c86a-49b3-a838-33001c7c0f18)

Please reopen.
