### ISSUE TITLE
M1: Translations Broken & Performance Decrease

### ISSUE THREAD

**Issue by sprankhub** [lyra/plugin-magento#10]
Yesterday we updated from `Lyra_Payzen` 1.7.1 to 1.9.2. We now encountered wrong translations and a decreased performance. The issues comes from `Lyra_Payzen_Model_Field_Translatable::afterLoad`:

1. Broken translations: No matter if in frontend or in backend, you reset the area of the translator to `adminhtml`:
https://github.com/payzen/plugin-magento/blob/7a43b84e2482ec88b7b3950faf9638fde7b720f1/app/code/community/Lyra/Payzen/Model/Field/Translatable.php#L43
This leads to the fact that certain strings are not translated into the correct locale in the frontend.
2. Performance Decrease: When `Mage::getStoreConfig` is called, your `afterLoad` method is called for every config value where `Lyra_Payzen_Model_Field_Translatable` is defined as a backend. There, you load the translations twice. This results in loading the translations 34 times!

Please fix this issue ASAP.

**Comment by nabil509** [comment]
Thank you for reporting. I agree with your explanation. **As workarround, you can just comment this part of code (lines 30-44) and save the plugin configuration after updating traslatable fields (as submodue titles).**

We done this code to quickly answer a marketing request about the translation of default values.

We will fix this as soon as possible.

**Comment by nabil509** [comment]
Hi, 

The translation of title is reverted in v1.9.3. The issue is fixed.

Thank you for reporting.
