### ISSUE TITLE
M1: Fatal Error On Order View

### ISSUE THREAD

**Issue by sprankhub** [lyra/plugin-magento#11]
A customer somehow canceled the payment process, so that we have a canceled order. If I open the order, I get the following fatal error:

    PHP Fatal error:  Uncaught Error: Class 'PayzenResponse' not found in /var/www/shop/htdocs/app/code/community/Lyra/Payzen/Block/Info.php:91
    Stack trace:
    #0 /var/www/shop/htdocs/app/design/adminhtml/default/default/template/payzen/info.phtml(48): Lyra_Payzen_Block_Info->getResultDescription()
    #1 /var/www/shop/htdocs/app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/silber...')
    #2 /var/www/shop/htdocs/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
    #3 /var/www/shop/htdocs/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
    #4 /var/www/shop/htdocs/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
    #5 /var/www/shop/htdocs/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()

**Comment by nabil509** [comment]
Thank you for reporting. It's an error in a case that occurs rarely (when there is a problem in payment form format).

Workarround: 
Please, goto file /var/www/shop/htdocs/app/code/community/Lyra/Payzen/Block/Info.php and replace PayzenResponse by Lyra_Payzen_Model_Api_Response to fix it.

We are working on a hotfix.

**Comment by nabil509** [comment]
Fixed in v1.9.3. I close issue.
