### ISSUE TITLE
Is the module compatible with magento 2.3 ?

### ISSUE THREAD

**Issue by LaboLescuyer** [lyra/plugin-magento#12]
Hi,

In the changelog, we see that you updated the module for Magento 2.2 but anywhere it is written that it's compatible with Magento 2.3.
Can you confirm or not that it's compatible ?
Thanks.

**Comment by nabil509** [comment]
Hi, 

Yes the module is compatible with Magento 2.3. There is no mention in changelog because this didn't need any update to make it compatible.

Please, ask PayZen support for such requests. GitHub issues are reserved for bug reporting.

Thank you.
