### ISSUE TITLE
Systempay Magento 1.4-1.9 v1.10.0

### ISSUE THREAD

**Issue by StevenHenriot** [lyra/plugin-magento#14]
When we make a credit card payment on the back office

`[error] 6149#6149: *207654 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'Lyranetwork\_Systempay\Model\Api\Ws\CommonRequest' not found in /var/www/magento1/includes/src/Lyranetwork_Systempay_Model_Payment_Standard.php on line 469" `

File : app\code\community\Lyranetwork\Systempay\Model\Payment\Standard.php
Method : _doInstantPayment
Line : 454

487 : $paymentRequest = new \Lyranetwork\_Systempay\Model\Api\Ws\PaymentRequest();
not _Systempay

**Comment by nabil509** [comment]
Hi, 

Thank you for reporting. Wi will fix it during the week.

**Comment by nabil509** [comment]
Hi,

The patch version 1.10.1 is released. I close issue.
