### ISSUE TITLE
[SEPA] is the RUM identifier available ?

### ISSUE THREAD

**Issue by fffab** [lyra/plugin-magento#15]
Hi,

maybe this is not an issue, more a question

we have payzen on both m1 and m2 stores

in m1, we had acces to the RUM generated by a SEPA transaction, and so we could export it, display it on customer order or account, etc...

in m2, this does not seems to be possible ?
did you switch to another system like the changelog suggest it ?

> [SEPA] Save SEPA aliases separately from CB payment aliases.

is a SEPA Alias the RUM we are looking for ?
if not, is there a way to get the RUM back in magento 2 ? in customer, order ?

Thanks for explainations,

Regards,

**Comment by nabil509** [comment]
Hi, 

SEPA alias is different from RUM. Both information are saved to the customer table. For the changlog entry you invoked, the update was to use different fields for bank card alias and for SEPA alias. That way, the merchant can propose bank card with payment with alias (1-click payment) and SEPA payment. 

For information, in the last versions of plugins for M1 and M2, we mask parts of the RUM for security reason. It is the responsibility of the merchant to modify the plugin and store the complete RUM.

Regards.

**Comment by nabil509** [comment]
I close because this is a support request, not an issue.
