### ISSUE TITLE
Wrong Payment URL

### ISSUE THREAD

**Issue by sprankhub** [lyra/plugin-magento#17]
When I am redirected to PayZen, I see the following error 

    Shop 12345 is not using the appropriate payment URL : https://secure.lyra.com

However, in the user guide, under "Payment page URL", it says:

> This field is pre-populated by default: https://secure.payzen.eu/

So what is the correct URL, which I should use?

**Comment by nabil509** [comment]
Hi,

This Github repository contains only PayZen offer plugin source code. Only our PayZen offer plugin can be installed using the Composer tool at this time.

According to the error message, you have a Lyra Collect payment offer. You should download the plugin ZIP from [here](https://github.com/lyra/plugin-magento/releases/download/v2.4.3/Lyra_Magento_2.x_v2.4.3.zip) and install it by following this [documentation](https://lyra.com/doc/files/module/doc/Lyra_Magento_2.x_v2.4_en.pdf). The right base URL for your offer is https://secure.lyra.com.

**Comment by sprankhub** [comment]
That is quite inconvenient!

1. How does a client or the client's technical agency know which extension to use in which case?
2. Is there really no way to install the "Lyra Collect payment offer extension" via Composer? Composer is the standard setup in M2, so this should really be possible!

**Comment by nabil509** [comment]
1. Lyra Collect and PayZen are two different sollutions. We give the client the link to the right online documentary site where he can donwload payment module. For Lyra Collect: https://lyra.com/en/doc/collect/free-payment-plugins/index.html#magento

2. You can try this method to install Lyra plugin using Composer:
- Add this description to the main Magento composer.json file, in the the "repositories" array entry:

```
,
{
    "type": "package",
    "package": {
        "name": "lyranetwork/module-lyra",
        "version": "v2.4.3",
        "dist": {
            "url": "https://github.com/lyra/plugin-magento/releases/download/v2.4.3/Lyra_Magento_2.x_v2.4.3.zip",
            "type": "zip"
        }
    }
}
```

- Using a command line, browse to the Magento root directory and run:
 composer require lyranetwork/module-lyra

**Comment by sprankhub** [comment]
I know that it is possible to define a zip-type package. However, this way, the module will never be updated via composer automatically. We need to track the changes manually and manually define an updated zip-type package then. This is not a proper solution.

**Comment by nabil509** [comment]
This is the only option we have at this time. We have to manage a unique source code in this repository and than generate many plugin packages for different offers/brands (for legal considerations). The maintenance of different repositories is not an option for us at this time. 

We will review this point later. I close this issue since there is already an open issue on packagist [here](https://github.com/lyra/plugin-magento/issues/1).

**Comment by sprankhub** [comment]
If anyone else needs to use the Lyra M2 module via composer:

The definition above is missing important stuff. This one may work:

    {
        "type": "package",
        "package": {
            "name": "lyranetwork/module-lyra",
            "version": "2.4.3",
            "dist": {
                "url": "https://github.com/lyra/plugin-magento/releases/download/v2.4.3/Lyra_Magento_2.x_v2.4.3.zip",
                "type": "zip"
            },
	        "require" : {
		        "php" : "~5.5.0|~5.6.0|~7"
	        },
            "type": "magento2-module",
	        "autoload" : {
		        "files" : [
			        "registration.php"
		        ],
		        "psr-4" : {
			        "Lyranetwork\\Lyra\\" : ""
		        }
	        },
        	"license" : "OSL-3.0"
        }
    }
