### ISSUE TITLE
Deprecated Functionality: Function get_magic_quotes_gpc() is deprecated

### ISSUE THREAD

**Issue by sprankhub** [lyra/plugin-magento#19]
The same change from https://github.com/lyra/plugin-magento/commit/aabc41e97a4954d5421bcd00abc6ac94f2495bb3 needs to be applied to the Magento 2 version as well. Otherwise, the payment notification fails due to the above mentioned error.

**Comment by nabil509** [comment]
Thank you for reporting. 

We are about to release v2.5.1 with this fix.

**Comment by nabil509** [comment]
We just released v2.5.1 with the fix. I close this issue.
