### ISSUE TITLE
Warning: Illegal string offset 'name'

### ISSUE THREAD

**Issue by mokadev** [lyra/plugin-magento#2]
Bonjour

Quand on utilise la fonctionnalité d'import de la configuration locale via la commande : 
`php bin/magento app:config:import`

on a un Warning généré par cette ligne: 
https://github.com/payzen/plugin-magento/blob/e840b7d7b4bede42e90bedaef83183e945ef175b/Model/System/Config/Backend/Logo.php#L26

Import failed: Warning: Illegal string offset 'name' in app/code/Lyranetwork/Payzen/Model/System/Config/Backend/Logo.php on line 26

parce que $this->getValue() retourne une string et non un array

**Comment by nabil509** [comment]
Bonjour, 

Merci pour cette remontée. Je vais vérifier cela et corriger dans la 2.1.4 en cours de développement.

**Comment by nabil509** [comment]
Issue fixed in version 2.1.4 in develop branch.
