### ISSUE TITLE
Bug with file FranfinancePaymentOptions.php

### ISSUE THREAD

**Issue by angelflo** [lyra/plugin-magento#22]
Hi, I backend when I try to configure the module by adding the shop id and secret key, when i click on save button I receive an error 

Something went wrong while saving this configuration: Notice: Undefined index: amount_max in /app/code/Lyranetwork/Payzen/Model/System/Config/Backend/Franfinance/FranfinancePaymentOptions.php on line 34

I don't want to use Franfinance, it's disable, but it display this error ... can you explain me why and how to fix it ??

For info I use last version 2.5.9 of your extension with magento 2.4.2-p1

**Comment by nberhouche** [comment]
Hi,

I think it's a problem during the installation or update of the module. Have you tried to reinstall it or to reset the module settings (By cliciking to the button in "Module Information" section) ?

Best regards,

**Comment by nberhouche** [comment]
Hi,

 In the last version of the plugin (v2.5.10), we added some data checks to avoid this kind of errors in the future.

Best regards.
