### ISSUE TITLE
Unknow constant  \Lyranetwork\Lyra\Helper\Payment::TOKEN_EXPIRE

### ISSUE THREAD

**Issue by nenes25** [lyra/plugin-magento#32]
Hello,

With the release of the version 2.7.0 the constant TOKEN_EXPIRE have been deleted from the class Lyranetwork\Lyra\Helper\Payment.

Due to this it's no more possible to use the embed integration on the checkout.
We have the following error message : 

Error: Undefined class constant 'TOKEN_EXPIRE' in /magento/app/code/Lyranetwork/Lyra/Model/Method/Standard.php:454

Regards,

**Comment by nberhouche** [comment]
Hello nenes25,
Thank you for bringing this issue to our attention, we'll look into it right away.

Best regards

**Comment by nberhouche** [comment]
Hello again,

It seems there is an issue with your installation of the plugin, and you are  using file Method/Standard.php from an older version of the plugin as there is no 'TOKEN_EXPIRE' anyware in the code of 2.7.0 version. Moreover, line  454 in app/code/Lyranetwork/Lyra/Model/Method/Standard.php uses "TOKEN_EXPIRE' in version 2.6.5, not in 2.7.0.

So it would be better to re-install the plugin, please check our documentation concerning plugin installation: https://payzen.io/en-EN/plugins/magento2/installing-the-payment-module.html.

Best regards

**Comment by nenes25** [comment]
Hello @nberhouche ,

Thanks for your update, i've checked our git history and you're right.
We have missed something during the module upgrade , it seems we have the old 2.6.5 file instead of the good one.
Sorry for the wrong issue,

Regards,
