### ISSUE TITLE
Deprecated functionnality error with PHP 8.2

### ISSUE THREAD

**Issue by jeromecx** [lyra/plugin-magento#34]
### Problem
This module doesn't work after migration to PHP 8.2.1.
### Steps to reproduce
- Upgrade to PHP 8.2.1
- Login to the admin
- Go to Stores > Settings > Configuration > Sales > Payment Methods from the Admin sidebar
### Actual result
```txt
1 exception(s):
Exception #0 (Exception): Deprecated Functionality: Creation of dynamic property Lyranetwork\Payzen\Model\System\Config\Source\GiftCard::$method is deprecated in /app/vendor/lyranetwork/module-payzen/Model/System/Config/Source/GiftCard.php on line 17
```
### Excpected result
Compatibility with php 8.2.x

**Comment by hchabane21** [comment]
Thank you for bringing this issue to our attention, we'll work on it.

**Comment by cpuchalver** [comment]
I'm facing the same isssue. I've found this as a workaround : [The AllowDynamicProperties class](https://www.php.net/manual/en/class.allowdynamicproperties.php).

The error is gone but I'm not sure about implications.

```php
<?php
/**
 * Copyright    Lyra Network.
 * This file is part of PayZen plugin for Magento 2. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
namespace Lyranetwork\Payzen\Model\System\Config\Source;

#[\AllowDynamicProperties]
class GiftCard implements \Magento\Framework\Option\ArrayInterface
{
    public function __construct(
        \Lyranetwork\Payzen\Model\Method\Gift $method
    ) {
        $this->method = $method;
    }

    public function toOptionArray()
    {
        $options =  [];

        foreach ($this->method->getSupportedCcTypes() as $code => $name) {
            $options[] = [
                'value' => $code,
                'label' => $code . ' - ' . $name
            ];
        }

        return $options;
    }
}
```

**Comment by nberhouche** [comment]
Hello there,

Thank you for you patience. We are a working on a hotfix to address this issue and other possible incompabilities with PHP 8.2.x
Wel''l keep you posted.

Best regards.

**Comment by jeromecx** [comment]
hello @nberhouche ,

Any news about this update ?
Please, could you give us a release date ?

Thank you in advance

**Comment by nberhouche** [comment]
Hello @jeromecx,

 It seems there was an oversight from our part, as the 2.7.2 version containing the fix has already been released (on the 24th of August, to be exact), we apologize for that and thank your for your patience.

Best regards.

**Comment by jeromecx** [comment]
This is a good news, thank you very much @nberhouche,
I'll close this issue
Regards,
