### ISSUE TITLE
Class "Zend\Http\PhpEnvironment\RemoteAddress" does not exist in Helper/Data.php

### ISSUE THREAD

**Issue by Djohn12** [lyra/plugin-magento#35]
Hi there team,

* lyra/pugin-magento ^2.8.0
* adobe commerce 2.4.6

Since magento 2.4.5 all the Zend framework classes have been deprecated.
As such, the usage of `Zend\Http\PhpEnvironment\RemoteAddress` in `Helper/Data.php` constructor produces a critical error.

Have you any plan to release a new version replacing that now non-existing class with the appropriate `Laminas\Http\PhpEnvironment\RemoteAddress` replacement ?

Thanks in advance,
Best Regards

**Comment by hchabane21** [comment]
Hello @Djohn12, 

Thank you for reporting this issue. In Magento 2.4.5, the Zend framework classes have indeed been deprecated and replaced with Laminas. We will make the necessary corrections in the future versions.

Best regards,

**Comment by Djohn12** [comment]
Seems there is also a usage of `Zend_Mail` in `Controller/Adminhtml/System/Config/Support.php`
This should probably be removed in favor of `Laminas\Mail\Message`

Hope this helps :)

**Comment by hchabane21** [comment]
Hello @Djohn12, 

We're so thankful for your help. We'll make the corrections for all the usage of the Zend framework classes.

Best regards,

**Comment by nberhouche** [comment]
Hello @Djohn12 ,

We've just released version 2.8.5 of the module that fixes the issue you've reported.
Thank you for your patience.

Best regards
