### ISSUE TITLE
Disabled report only mode for CSP blocks every external resource if not whitelisted

### ISSUE THREAD

**Issue by norgeindian** [lyra/plugin-magento#43]
Please be so kind and take a look into `etc/config.xml`.
The following disabled the report only mode for the entire storefront:

```
        <csp>
            <mode>
                <storefront>
                    <report_only>0</report_only>
                </storefront>
                <admin>
                    <report_only>0</report_only>
                </admin>
            </mode>
        </csp>
```
That means, that every external resource is directly blocked, if it is not whitelisted, no matter which module tries to load it.
Please be so kind and remove this setting again.

**Comment by nberhouche** [comment]
Hello @norgeindian ,

Thank you for bringing this issue to our attention. We'll get to it as soona s possible.


Best regards

**Comment by GIMALima** [comment]
Hello,

The issue was resolved in our latest version.

Best regards.
