### ISSUE TITLE
Critical: Unable to get content for Lyranetwork_Payzen/css/payzen.css

### ISSUE THREAD

**Issue by lbajsarowicz** [lyra/plugin-magento#5]
### Log entry

`[2018-03-07 15:09:23] report.CRITICAL: Unable to get content for 'frontend/Magento/.../fr_FR/Lyranetwork_Payzen/css/payzen.css' {"exception":"[object] (Magento\\Framework\\View\\Asset\\File\\NotFoundException(code: 0): Unable to get content for 'frontend/Magento/.../fr_FR/Lyranetwork_Payzen/css/payzen.css' at /var/www/html/vendor/magento/framework/View/Asset/File.php:186)"} []`

**Comment by lbajsarowicz** [comment]
Created Pull Request with fix for that: https://github.com/payzen/plugin-magento/pull/6

**Comment by nabil509** [comment]
PR accepted and merged to develop. I close issue.

Thank you.
